version: '3.3'
services:
        nginx-service:
                image: nginx:latest
                volumes:
                 - /var/www/html:/usr/share/nginx/html
                ports:
                 - 8082:80
                 - 8083:443
                networks:
                 - frontend
        apache-service:
                image: httpd:latest
                ports:
                 - 8084:80
                networks:
                 - frontend
        adminer-service:
                image: adminer
                ports:
                 - 8080:8080
                networks:
                 - backend
                 - frontend
        mysql-db-service:
                image: mysql:latest
                command: --default-authentication-plugin=mysql_native_password
                ports:
                 - 3307:3306
                networks:
                 - backend
                environment:
                 MYSQL_ROOT_PASSWORD: root
                 MYSQL_DATABASE: infraroot

networks:
 frontend:
  driver: bridge
 backend:
  driver: bridge
